### PR TITLE
Create linter_zig.lua

### PR DESCRIPTION
**Pull request by VarLad**
Linter config for the Zig Language

### CODE REVIEW

**Comment by drmargarido** [comment]
Thanks for you pull request.
Before merging the linter I would just ask you to add the linter description in the readme.
Also keep the readme linters in alphabetical order.

**Comment by VarLad** [comment]
Done?

**Comment by VarLad** [comment]
@drmargarido I hope you don't mind me asking this here....
Is there any way to run the linter automatically? (not just on saving?)

**Comment by drmargarido** [comment]
At the moment we are not exposing any command to run it manually but it would be a simple thing to do. In which situations you want to run it?

**Comment by VarLad** [comment]
Normally, I want the code the code to be lint as I'm writing. Zig's linter is fast enough for this

Autosaving is another alternative, but its slow and I personally don't want to save on every type

**Comment by VarLad** [comment]
So @drmargarido if this a trivial feature, then should I open a feature request for this?

**Comment by VarLad** [comment]
Also, I hope you don't mind this one as well, is there any way to change the font of the error from linter? :sweat_smile:

**Comment by drmargarido** [comment]
Yes, it's simple to add. I just think that it will probably not work with most linters, some of them are slow. Others just go for the full project and that takes time. I'm not sure if I should add that as a configuration or just expose a manual command to activate the linter and then allow people to do that kind of thing from their user module. Anyway it can be supported.

linters use the lite base fonts, to change them you can edit your [style](https://github.com/rxi/lite/blob/master/data/core/style.lua#L10) file, or override the font in your user module.

**Comment by drmargarido** [comment]
If you want just to change the font inside the warning window that is not supported yet but is also easy to be added.

**Comment by VarLad** [comment]
@drmargarido Would be nice to have both the features :smile: 

For the first issue, I think it depends on language to language. Plus if you make it an option, and if the project gets really big and it starts slowing down, users can just turn it off.

For the second issue, I think I can change the base for now, but if its trivial, havning an option to change the warning font would be much appreciated :smile: 

Well, thanks again.

**Comment by VarLad** [comment]
Ah, one more question
Is there any plan for supporting different levels? (with color?) (Like error, warning etc. I've already checked out lintplus, just asking for this one)

**Comment by drmargarido** [comment]
I'm not planning on adding it at the moment.
To implement that some refactor is needed in the match and render parts of the code and we would need a revision to every linter.
It's not that hard by itself but takes some time to do it and test everything is ok, and I have multiple things I'm working on at the same time.
If someone volunteers for that I would take it gladly :smile:

**Comment by drmargarido** [comment]
Also I was thinking about cleaning and simplifying the code a bit before any major changes, after receiving pull requests from multiple people that just look at specific parts of the code, it is a bit confusing with too many jumps from place to place without need.

**Pull request merged**
